In [1]:
!pip install yfinance

Requirement already satisfied: yfinance in /Library/anaconda3/lib/python3.13/site-packages (1.1.0)
Requirement already satisfied: pandas>=1.3.0 in /Library/anaconda3/lib/python3.13/site-packages (from yfinance) (2.3.3)
Requirement already satisfied: numpy>=1.16.5 in /Library/anaconda3/lib/python3.13/site-packages (from yfinance) (2.3.5)
Requirement already satisfied: requests>=2.31 in /Library/anaconda3/lib/python3.13/site-packages (from yfinance) (2.32.5)
Requirement already satisfied: multitasking>=0.0.7 in /Library/anaconda3/lib/python3.13/site-packages (from yfinance) (0.0.12)
Requirement already satisfied: platformdirs>=2.0.0 in /Library/anaconda3/lib/python3.13/site-packages (from yfinance) (4.5.0)
Requirement already satisfied: pytz>=2022.5 in /Library/anaconda3/lib/python3.13/site-packages (from yfinance) (2025.2)
Requirement already satisfied: frozendict>=2.3.4 in /Library/anaconda3/lib/python3.13/site-packages (from yfinance) (2.4.6)
Requirement already satisfied: peewee>=3.16.2 in /Library/anaconda3/lib/python3.13/site-packages (from yfinance) (3.19.0)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /Library/anaconda3/lib/python3.13/site-packages (from yfinance) (4.13.5)
Requirement already satisfied: curl_cffi<0.14,>=0.7 in /Library/anaconda3/lib/python3.13/site-packages (from yfinance) (0.13.0)
Requirement already satisfied: protobuf>=3.19.0 in /Library/anaconda3/lib/python3.13/site-packages (from yfinance) (5.29.3)
Requirement already satisfied: websockets>=13.0 in /Library/anaconda3/lib/python3.13/site-packages (from yfinance) (16.0)
Requirement already satisfied: cffi>=1.12.0 in /Library/anaconda3/lib/python3.13/site-packages (from curl_cffi<0.14,>=0.7->yfinance) (2.0.0)
Requirement already satisfied: certifi>=2024.2.2 in /Library/anaconda3/lib/python3.13/site-packages (from curl_cffi<0.14,>=0.7->yfinance) (2025.11.12)
Requirement already satisfied: soupsieve>1.2 in /Library/anaconda3/lib/python3.13/site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.5)
Requirement already satisfied: typing-extensions>=4.0.0 in /Library/anaconda3/lib/python3.13/site-packages (from beautifulsoup4>=4.11.1->yfinance) (4.15.0)
Requirement already satisfied: pycparser in /Library/anaconda3/lib/python3.13/site-packages (from cffi>=1.12.0->curl_cffi<0.14,>=0.7->yfinance) (2.23)
Requirement already satisfied: python-dateutil>=2.8.2 in /Library/anaconda3/lib/python3.13/site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /Library/anaconda3/lib/python3.13/site-packages (from pandas>=1.3.0->yfinance) (2025.2)
Requirement already satisfied: six>=1.5 in /Library/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /Library/anaconda3/lib/python3.13/site-packages (from requests>=2.31->yfinance) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /Library/anaconda3/lib/python3.13/site-packages (from requests>=2.31->yfinance) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Library/anaconda3/lib/python3.13/site-packages (from requests>=2.31->yfinance) (2.5.0)

In [2]:
import pandas as pd
import numpy as np
import yfinance as yf

%matplotlib inline

In [3]:
aapl=yf.Ticker('AAPL')

In [4]:
aapl

yfinance.Ticker object <AAPL>

In [5]:
aapl.history()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2026-01-14 00:00:00-05:00,259.247418,261.575257,256.470018,259.716980,40019400,0.00,0.0
2026-01-15 00:00:00-05:00,260.406319,260.795969,256.809678,257.968597,39388600,0.00,0.0
2026-01-16 00:00:00-05:00,257.658902,258.657967,254.691677,255.291122,72142800,0.00,0.0
2026-01-20 00:00:00-05:00,252.493737,254.551809,243.192443,246.469376,80267500,0.00,0.0
2026-01-21 00:00:00-05:00,248.467509,251.324836,244.950795,247.418488,54641700,0.00,0.0
2026-01-22 00:00:00-05:00,248.967040,250.765360,247.918018,248.117844,39708300,0.00,0.0
2026-01-23 00:00:00-05:00,247.088808,249.176850,244.451261,247.808121,41689000,0.00,0.0
2026-01-26 00:00:00-05:00,251.244900,256.320153,249.566478,255.171234,55969200,0.00,0.0
2026-01-27 00:00:00-05:00,258.927717,261.705117,257.968592,258.028534,49648300,0.00,0.0
2026-01-28 00:00:00-05:00,257.409147,258.618008,254.272083,256.200287,41288000,0.00,0.0
2026-01-29 00:00:00-05:00,257.758807,259.407258,254.172166,258.038544,67253000,0.00,0.0
2026-01-30 00:00:00-05:00,254.931443,261.655147,251.944233,259.237427,92443400,0.00,0.0
2026-02-02 00:00:00-05:00,259.786917,270.237131,258.967677,269.757599,73913400,0.00,0.0
2026-02-03 00:00:00-05:00,268.948351,271.625839,267.359811,269.228088,64394700,0.00,0.0
2026-02-04 00:00:00-05:00,272.035451,278.689229,272.035451,276.231506,90545700,0.00,0.0
2026-02-05 00:00:00-05:00,277.869995,279.238709,272.974582,275.652069,52977400,0.00,0.0
2026-02-06 00:00:00-05:00,276.860920,280.647386,276.671095,277.859985,50453400,0.00,0.0
2026-02-09 00:00:00-05:00,277.910004,278.200012,271.700012,274.619995,44623400,0.26,0.0
2026-02-10 00:00:00-05:00,274.890015,275.369995,272.940002,273.679993,34376900,0.00,0.0
2026-02-11 00:00:00-05:00,274.700012,280.179993,274.450012,275.500000,51931300,0.00,0.0
2026-02-12 00:00:00-05:00,275.589996,275.720001,260.179993,261.730011,81077200,0.00,0.0
2026-02-13 00:00:00-05:00,262.010010,262.230011,255.449997,255.779999,56229900,0.00,0.0

In [6]:
aapl.history().shape

(22, 7)

In [7]:
days = 20
hist = aapl.history(period = f'{days}d')
hist

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2026-01-16 00:00:00-05:00,257.658902,258.657967,254.691677,255.291122,72142800,0.00,0.0
2026-01-20 00:00:00-05:00,252.493737,254.551809,243.192443,246.469376,80267500,0.00,0.0
2026-01-21 00:00:00-05:00,248.467509,251.324836,244.950795,247.418488,54641700,0.00,0.0
2026-01-22 00:00:00-05:00,248.967040,250.765360,247.918018,248.117844,39708300,0.00,0.0
2026-01-23 00:00:00-05:00,247.088808,249.176850,244.451261,247.808121,41689000,0.00,0.0
2026-01-26 00:00:00-05:00,251.244900,256.320153,249.566478,255.171234,55969200,0.00,0.0
2026-01-27 00:00:00-05:00,258.927717,261.705117,257.968592,258.028534,49648300,0.00,0.0
2026-01-28 00:00:00-05:00,257.409147,258.618008,254.272083,256.200287,41288000,0.00,0.0
2026-01-29 00:00:00-05:00,257.758807,259.407258,254.172166,258.038544,67253000,0.00,0.0
2026-01-30 00:00:00-05:00,254.931443,261.655147,251.944233,259.237427,92443400,0.00,0.0
2026-02-02 00:00:00-05:00,259.786917,270.237131,258.967677,269.757599,73913400,0.00,0.0
2026-02-03 00:00:00-05:00,268.948351,271.625839,267.359811,269.228088,64394700,0.00,0.0
2026-02-04 00:00:00-05:00,272.035451,278.689229,272.035451,276.231506,90545700,0.00,0.0
2026-02-05 00:00:00-05:00,277.869995,279.238709,272.974582,275.652069,52977400,0.00,0.0
2026-02-06 00:00:00-05:00,276.860920,280.647386,276.671095,277.859985,50453400,0.00,0.0
2026-02-09 00:00:00-05:00,277.910004,278.200012,271.700012,274.619995,44623400,0.26,0.0
2026-02-10 00:00:00-05:00,274.890015,275.369995,272.940002,273.679993,34376900,0.00,0.0
2026-02-11 00:00:00-05:00,274.700012,280.179993,274.450012,275.500000,51931300,0.00,0.0
2026-02-12 00:00:00-05:00,275.589996,275.720001,260.179993,261.730011,81077200,0.00,0.0
2026-02-13 00:00:00-05:00,262.010010,262.230011,255.449997,255.779999,56229900,0.00,0.0

In [7]:
hist.columns

Index(['Open', 'High', 'Low', 'Close', 'Volume', 'Dividends', 'Stock Splits'], dtype='object')

In [8]:
hist.reset_index()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,2026-01-16 00:00:00-05:00,257.658902,258.657967,254.691677,255.291122,72142800,0.00,0.0
1,2026-01-20 00:00:00-05:00,252.493737,254.551809,243.192443,246.469376,80267500,0.00,0.0
2,2026-01-21 00:00:00-05:00,248.467509,251.324836,244.950795,247.418488,54641700,0.00,0.0
3,2026-01-22 00:00:00-05:00,248.967040,250.765360,247.918018,248.117844,39708300,0.00,0.0
4,2026-01-23 00:00:00-05:00,247.088808,249.176850,244.451261,247.808121,41689000,0.00,0.0
5,2026-01-26 00:00:00-05:00,251.244900,256.320153,249.566478,255.171234,55969200,0.00,0.0
6,2026-01-27 00:00:00-05:00,258.927717,261.705117,257.968592,258.028534,49648300,0.00,0.0
7,2026-01-28 00:00:00-05:00,257.409147,258.618008,254.272083,256.200287,41288000,0.00,0.0
8,2026-01-29 00:00:00-05:00,257.758807,259.407258,254.172166,258.038544,67253000,0.00,0.0
9,2026-01-30 00:00:00-05:00,254.931443,261.655147,251.944233,259.237427,92443400,0.00,0.0
10,2026-02-02 00:00:00-05:00,259.786917,270.237131,258.967677,269.757599,73913400,0.00,0.0
11,2026-02-03 00:00:00-05:00,268.948351,271.625839,267.359811,269.228088,64394700,0.00,0.0
12,2026-02-04 00:00:00-05:00,272.035451,278.689229,272.035451,276.231506,90545700,0.00,0.0
13,2026-02-05 00:00:00-05:00,277.869995,279.238709,272.974582,275.652069,52977400,0.00,0.0
14,2026-02-06 00:00:00-05:00,276.860920,280.647386,276.671095,277.859985,50453400,0.00,0.0
15,2026-02-09 00:00:00-05:00,277.910004,278.200012,271.700012,274.619995,44623400,0.26,0.0
16,2026-02-10 00:00:00-05:00,274.890015,275.369995,272.940002,273.679993,34376900,0.00,0.0
17,2026-02-11 00:00:00-05:00,274.700012,280.179993,274.450012,275.500000,51931300,0.00,0.0
18,2026-02-12 00:00:00-05:00,275.589996,275.720001,260.179993,261.730011,81077200,0.00,0.0
19,2026-02-13 00:00:00-05:00,262.010010,262.230011,255.449997,255.779999,56229900,0.00,0.0

In [9]:
hist_msft = yf.Ticker('MSFT').history(period=f'{days}d')
hist_msft

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2026-01-16 00:00:00-05:00,457.829987,463.190002,456.480011,459.859985,34246700,0.0,0.0
2026-01-20 00:00:00-05:00,451.220001,456.799988,449.279999,454.519989,26130000,0.0,0.0
2026-01-21 00:00:00-05:00,452.600006,452.690002,438.679993,444.109985,37980500,0.0,0.0
2026-01-22 00:00:00-05:00,447.619995,452.839996,444.700012,451.140015,25349400,0.0,0.0
2026-01-23 00:00:00-05:00,451.869995,471.100006,450.529999,465.950012,38000200,0.0,0.0
2026-01-26 00:00:00-05:00,465.309998,474.250000,462.000000,470.279999,29291200,0.0,0.0
2026-01-27 00:00:00-05:00,473.700012,482.869995,473.160004,480.579987,29213900,0.0,0.0
2026-01-28 00:00:00-05:00,483.209991,483.739990,478.000000,481.630005,36875400,0.0,0.0
2026-01-29 00:00:00-05:00,439.989990,442.500000,421.019989,433.500000,128855300,0.0,0.0
2026-01-30 00:00:00-05:00,439.170013,439.600006,426.450012,430.290009,58566800,0.0,0.0
2026-02-02 00:00:00-05:00,430.239990,430.739990,422.250000,423.369995,42219900,0.0,0.0
2026-02-03 00:00:00-05:00,422.010010,422.049988,408.559998,411.209991,61424100,0.0,0.0
2026-02-04 00:00:00-05:00,411.000000,419.799988,409.239990,414.190002,45012400,0.0,0.0
2026-02-05 00:00:00-05:00,407.440002,408.299988,392.320007,393.670013,66289200,0.0,0.0
2026-02-06 00:00:00-05:00,399.170013,401.790009,392.920013,401.140015,53515300,0.0,0.0
2026-02-09 00:00:00-05:00,404.850006,414.890015,400.869995,413.600006,45480500,0.0,0.0
2026-02-10 00:00:00-05:00,419.619995,423.679993,412.700012,413.269989,44857900,0.0,0.0
2026-02-11 00:00:00-05:00,416.179993,416.459991,401.010010,404.369995,42491000,0.0,0.0
2026-02-12 00:00:00-05:00,405.000000,406.200012,398.010010,401.839996,40802400,0.0,0.0
2026-02-13 00:00:00-05:00,404.450012,405.540009,398.049988,401.320007,34041200,0.0,0.0

In [10]:
pd.concat([hist, hist_msft], axis=1).head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,,,,,,,,
2026-01-16 00:00:00-05:00,257.658902,258.657967,254.691677,255.291122,72142800,0.0,0.0,457.829987,463.190002,456.480011,459.859985,34246700,0.0,0.0
2026-01-20 00:00:00-05:00,252.493737,254.551809,243.192443,246.469376,80267500,0.0,0.0,451.220001,456.799988,449.279999,454.519989,26130000,0.0,0.0
2026-01-21 00:00:00-05:00,248.467509,251.324836,244.950795,247.418488,54641700,0.0,0.0,452.600006,452.690002,438.679993,444.109985,37980500,0.0,0.0
2026-01-22 00:00:00-05:00,248.967040,250.765360,247.918018,248.117844,39708300,0.0,0.0,447.619995,452.839996,444.700012,451.140015,25349400,0.0,0.0
2026-01-23 00:00:00-05:00,247.088808,249.176850,244.451261,247.808121,41689000,0.0,0.0,451.869995,471.100006,450.529999,465.950012,38000200,0.0,0.0

In [11]:
hist.head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2026-01-16 00:00:00-05:00,257.658902,258.657967,254.691677,255.291122,72142800,0.0,0.0
2026-01-20 00:00:00-05:00,252.493737,254.551809,243.192443,246.469376,80267500,0.0,0.0
2026-01-21 00:00:00-05:00,248.467509,251.324836,244.950795,247.418488,54641700,0.0,0.0
2026-01-22 00:00:00-05:00,248.967040,250.765360,247.918018,248.117844,39708300,0.0,0.0
2026-01-23 00:00:00-05:00,247.088808,249.176850,244.451261,247.808121,41689000,0.0,0.0

In [12]:
hist.index

DatetimeIndex(['2026-01-16 00:00:00-05:00', '2026-01-20 00:00:00-05:00',
               '2026-01-21 00:00:00-05:00', '2026-01-22 00:00:00-05:00',
               '2026-01-23 00:00:00-05:00', '2026-01-26 00:00:00-05:00',
               '2026-01-27 00:00:00-05:00', '2026-01-28 00:00:00-05:00',
               '2026-01-29 00:00:00-05:00', '2026-01-30 00:00:00-05:00',
               '2026-02-02 00:00:00-05:00', '2026-02-03 00:00:00-05:00',
               '2026-02-04 00:00:00-05:00', '2026-02-05 00:00:00-05:00',
               '2026-02-06 00:00:00-05:00', '2026-02-09 00:00:00-05:00',
               '2026-02-10 00:00:00-05:00', '2026-02-11 00:00:00-05:00',
               '2026-02-12 00:00:00-05:00', '2026-02-13 00:00:00-05:00'],
              dtype='datetime64[ns, America/New_York]', name='Date', freq=None)

In [13]:
hist.index = hist.index.strftime('%d %B %Y')

In [14]:
hist.head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
16 January 2026,257.658902,258.657967,254.691677,255.291122,72142800,0.0,0.0
20 January 2026,252.493737,254.551809,243.192443,246.469376,80267500,0.0,0.0
21 January 2026,248.467509,251.324836,244.950795,247.418488,54641700,0.0,0.0
22 January 2026,248.967040,250.765360,247.918018,248.117844,39708300,0.0,0.0
23 January 2026,247.088808,249.176850,244.451261,247.808121,41689000,0.0,0.0

In [15]:
hist = hist[['Close']]
hist.columns = ['apple']
hist.head()

                      apple
Date
16 January 2026  255.291122
20 January 2026  246.469376
21 January 2026  247.418488
22 January 2026  248.117844
23 January 2026  247.808121

In [16]:
hist =hist.T
hist

Date,16 January 2026,20 January 2026,21 January 2026,22 January 2026,23 January 2026,26 January 2026,27 January 2026,28 January 2026,29 January 2026,30 January 2026,02 February 2026,03 February 2026,04 February 2026,05 February 2026,06 February 2026,09 February 2026,10 February 2026,11 February 2026,12 February 2026,13 February 2026
apple,255.291122,246.469376,247.418488,248.117844,247.808121,255.171234,258.028534,256.200287,258.038544,259.237427,269.757599,269.228088,276.231506,275.652069,277.859985,274.619995,273.679993,275.5,261.730011,255.779999

In [17]:
hist.index.name = 'Name'

In [18]:
hist

Date,16 January 2026,20 January 2026,21 January 2026,22 January 2026,23 January 2026,26 January 2026,27 January 2026,28 January 2026,29 January 2026,30 January 2026,02 February 2026,03 February 2026,04 February 2026,05 February 2026,06 February 2026,09 February 2026,10 February 2026,11 February 2026,12 February 2026,13 February 2026
Name,,,,,,,,,,,,,,,,,,,,
apple,255.291122,246.469376,247.418488,248.117844,247.808121,255.171234,258.028534,256.200287,258.038544,259.237427,269.757599,269.228088,276.231506,275.652069,277.859985,274.619995,273.679993,275.5,261.730011,255.779999